### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/web-memo#8]
### TODOs
- [x] CI
- [x] ~~Unit tests~~ Won't do it
- [x] ~~Code coverage~~ Won't do it
- [x] Type checks, prettier
